/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "kernel.h"
#include "BSP.h"
#define QUANTA 10
uint32_t task0_wTime;
uint32_t task1_wTime;
uint32_t task2_wTime;
uint32_t pTask0_wTime;
uint32_t pTask1_wTime;
uint32_t pTask2_wTime;

uint32_t adc_val;
int32_t s1, s2;

Semaphore uart;
Signal mbox1, mbox2;
Queue_t q1, q2;
uint32_t data;
uint32_t getData;

/* MailSend ve Dolayli Olarak Signal Testi
void task0(void)
{
	int adc_deger = 0;
	while(1)
	{
		adc_deger = BSP_ADC1_Read();
		if(adc_deger > 2048)
			MailSend(&mbox1, &q1, adc_deger);
		else
			BSP_USER_LED_OFF();
		task0_wTime++;
	}
}
void task1(void)
{
	int adc_deger_mbox;
	while(1)
	{
		adc_deger_mbox = MailReceive(&mbox1, &q1);

		if(adc_deger_mbox > 3250)
			MailSend(&mbox2, &q2, adc_deger_mbox);
		task1_wTime++;
	}
}
int adc_deger_son = 0;

void task2(void)
{
	while(1)
	{
		adc_deger_son = MailReceive(&mbox2, &q2);

		if(adc_deger_son > 3600)
			BSP_USER_LED_ON();
		else
			BSP_USER_LED_OFF();
		task2_wTime++;
	}
}
*/

void task0(void)
{
	while(1)
	{
		SemaphoreGet(&uart);
		uprint("TASK0\r\n");
		SemaphoreRelease(&uart);
		task0_wTime++;
	}
}

void task1(void)
{
	while(1)
	{
		SemaphoreGet(&uart);
		uprint("TASK1\r\n");
		SemaphoreRelease(&uart);
		task1_wTime++;
	}
}

void task2(void)
{
	while(1)
	{
		SemaphoreGet(&uart);
		uprint("TASK2\r\n");
		SemaphoreRelease(&uart);
		task2_wTime++;
	}
}

void pTask0(void)
{

	pTask0_wTime++;

}
void pTask1(void)
{

	pTask1_wTime++;

}

void pTask2(void)
{

	pTask2_wTime++;
}

int main(void)
{
	BSP_ADC1_INIT();
	BSP_LED_INIT();
	UART_INIT();
	SemaphoreInit(&uart);
	SignalInit(&mbox1, 0);
	SignalInit(&mbox2, 0);
	QueueInit(&q1);
	QueueInit(&q2);
	kernel_init();
	add_thread(task0, 0);
	add_thread(task1, 7);
	add_thread(task2, 11);
	add_periodic_thread(pTask0, 75);
	add_periodic_thread(pTask1, 400);
	add_periodic_thread(pTask2, 500);

	kernel_launch(QUANTA);
    /* Loop forever */
	for(;;);
}
